### ISSUE TITLE
Update the phantomjs version in package.json

### ISSUE THREAD

**Issue by lagden** [sindresorhus/phantom-bridge#2]
Hi @sindresorhus 

I were using `pageres` to get screenshots of my website, but I am using `flexbox` and not works!! :cry:

So, I make some tests with the last version of `phantomjs 2.0.0` and :metal:
Can you update for us?

**Comment by sindresorhus** [comment]
I would really like to, but can't: https://github.com/sindresorhus/pageres/issues/77 ...

**Comment by lagden** [comment]
I understand!!
The hole is much more deep!!
