### ISSUE TITLE
Always use latest PhantomJS version?

### ISSUE THREAD

**Issue by rafaelrinaldi** [sindresorhus/phantom-bridge#3]
Hey, just a QQ. Today this module will lock the dependency on PhantomJS version `1.9.2-6`. What if there's a way of always using the latest version available (which as for today would be `2.0.1`).

**Comment by sindresorhus** [comment]
The latest precompiled PhantomJS is 1.9.18: https://github.com/Medium/phantomjs/releases

More on that here: https://github.com/sindresorhus/pageres/issues/77
